/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yourcad;

/**
 *
 * @author info-chefe
 */
public class FormPesqCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormPesqCliente
     */
    public FormPesqCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Principal = new javax.swing.JMenuBar();
        Menu_Cadastro = new javax.swing.JMenu();
        Menu_CadCliente = new javax.swing.JMenuItem();
        Menu_CadConta = new javax.swing.JMenuItem();
        Menu_CadConcessionaria = new javax.swing.JMenuItem();
        Menu_Pesquisa = new javax.swing.JMenu();
        Menu_PesqCliente = new javax.swing.JMenuItem();
        Menu_PesqConta = new javax.swing.JMenuItem();
        Menu_PesqConcessionaria = new javax.swing.JMenuItem();
        Menu_Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 768));

        Menu_Cadastro.setText("CADASTRO");
        Menu_Cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Cadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Menu_Cadastro.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Menu_CadastroMenuSelected(evt);
            }
        });

        Menu_CadCliente.setText("CLIENTE");
        Menu_CadCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_CadClienteMouseClicked(evt);
            }
        });
        Menu_CadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_CadClienteActionPerformed(evt);
            }
        });
        Menu_Cadastro.add(Menu_CadCliente);

        Menu_CadConta.setText("CONTA");
        Menu_CadConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_CadContaActionPerformed(evt);
            }
        });
        Menu_Cadastro.add(Menu_CadConta);

        Menu_CadConcessionaria.setText("CONCESSIONÁRIA");
        Menu_CadConcessionaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_CadConcessionariaActionPerformed(evt);
            }
        });
        Menu_Cadastro.add(Menu_CadConcessionaria);

        Menu_Principal.add(Menu_Cadastro);

        Menu_Pesquisa.setText("PESQUISA");

        Menu_PesqCliente.setText("CLIENTE");
        Menu_PesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PesqClienteActionPerformed(evt);
            }
        });
        Menu_Pesquisa.add(Menu_PesqCliente);

        Menu_PesqConta.setText("CONTA");
        Menu_PesqConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PesqContaActionPerformed(evt);
            }
        });
        Menu_Pesquisa.add(Menu_PesqConta);

        Menu_PesqConcessionaria.setText("CONCESSIONARIA");
        Menu_PesqConcessionaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PesqConcessionariaActionPerformed(evt);
            }
        });
        Menu_Pesquisa.add(Menu_PesqConcessionaria);

        Menu_Principal.add(Menu_Pesquisa);

        Menu_Sair.setText("SAIR");
        Menu_Principal.add(Menu_Sair);

        setJMenuBar(Menu_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_CadClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_CadClienteMouseClicked
        // TODO add your handling code here:
        new FormCadCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_CadClienteMouseClicked

    private void Menu_CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_CadClienteActionPerformed
        // TODO add your handling code here:
        new FormCadCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_CadClienteActionPerformed

    private void Menu_CadContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_CadContaActionPerformed
        // TODO add your handling code here:
        new FormCadConta().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_CadContaActionPerformed

    private void Menu_CadConcessionariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_CadConcessionariaActionPerformed
        // TODO add your handling code here:
        new FormCadConcessionaria().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_CadConcessionariaActionPerformed

    private void Menu_CadastroMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Menu_CadastroMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_CadastroMenuSelected

    private void Menu_PesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PesqClienteActionPerformed
        // TODO add your handling code here:
        new FormPesqCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_PesqClienteActionPerformed

    private void Menu_PesqContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PesqContaActionPerformed
        // TODO add your handling code here:
        new FormPesqConta().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_PesqContaActionPerformed

    private void Menu_PesqConcessionariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PesqConcessionariaActionPerformed
        // TODO add your handling code here:
        new FormPesqConcessionaria().setVisible(true);
        dispose();
    }//GEN-LAST:event_Menu_PesqConcessionariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesqCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_CadCliente;
    private javax.swing.JMenuItem Menu_CadConcessionaria;
    private javax.swing.JMenuItem Menu_CadConta;
    private javax.swing.JMenu Menu_Cadastro;
    private javax.swing.JMenuItem Menu_PesqCliente;
    private javax.swing.JMenuItem Menu_PesqConcessionaria;
    private javax.swing.JMenuItem Menu_PesqConta;
    private javax.swing.JMenu Menu_Pesquisa;
    private javax.swing.JMenuBar Menu_Principal;
    private javax.swing.JMenu Menu_Sair;
    // End of variables declaration//GEN-END:variables
}
