/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp1_e5;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MaXx
 */
public class Form_Profissional extends javax.swing.JFrame {

    /**
     * Creates new form Form_Profissional
     */
    public Form_Profissional() throws Exception {
        initComponents();
        PopularJTable();
    }
    public void PopularJTable() throws Exception 
    {
        try
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
            conn = DBConexao.abrirConexao();
            Statement stm = conn.createStatement();
                
            String sql0;
            sql0 = "SELECT * FROM profissional ";
            resultadoBanco = stm.executeQuery(sql0);
         
            DefaultTableModel model =(DefaultTableModel) tbview_Profissional.getModel();
            model.setNumRows(0);

            while(resultadoBanco.next())
            {
                model.addRow(new Object[] 
                { 
                   //retorna os dados da tabela do BD, cada campo e um coluna.
                   resultadoBanco.getString("profissional_id"),
                   resultadoBanco.getString("profissional_nome"),
                   resultadoBanco.getString("profissional_profissao"),
                   resultadoBanco.getString("profissional_salario"),
                   resultadoBanco.getString("profissional_areaAtuacao"),
                   resultadoBanco.getString("profissional_cargo")
                }); 
            } 

        }
       catch (SQLException ex){System.out.println("o erro foi " +ex);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ProfissionalId = new javax.swing.JTextField();
        txt_ProfissionalCargo = new javax.swing.JTextField();
        txt_ProfissionalAreaAtuacao = new javax.swing.JTextField();
        txt_ProfissionalNome = new javax.swing.JTextField();
        txt_ProfissionalProfissao = new javax.swing.JTextField();
        txt_ProfissionalSalario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_limpar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        btn_pesq = new javax.swing.JButton();
        txt_ProfissionalPesqNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ProfissionalPesqProfissao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbview_Profissional = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_ProfissionalId.setEditable(false);
        txt_ProfissionalId.setText("0");

        txt_ProfissionalNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProfissionalNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME:");

        jLabel2.setText("SALÁRIO:");

        jLabel3.setText("PROFISSÃO:");

        jLabel4.setText("AREA DE ATUAÇÃO:");

        jLabel5.setText("CARGO:");

        btn_limpar.setText("LIMPAR");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_salvar.setText("SALVAR");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_voltar.setText("VOLTAR");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_deletar.setText("DELETAR");
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        btn_pesq.setText("PESQUISAR");
        btn_pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesqActionPerformed(evt);
            }
        });

        txt_ProfissionalPesqNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProfissionalPesqNomeActionPerformed(evt);
            }
        });

        jLabel6.setText("NOME:");

        jLabel7.setText("PROFISSÃO:");

        tbview_Profissional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "PROFISSÃO", "SALÁRIO", "AREA DE ATUAÇÃO", "CARGO"
            }
        ));
        tbview_Profissional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbview_ProfissionalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbview_Profissional);

        jLabel8.setText("FORMULÁRIO DE PROFISSIONAIS");

        jLabel9.setText("PESQUISA DE PROFISSIONAIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txt_ProfissionalId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btn_limpar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ProfissionalSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_ProfissionalProfissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addComponent(txt_ProfissionalCargo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txt_ProfissionalNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ProfissionalAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btn_salvar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_voltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_ProfissionalPesqProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_ProfissionalPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_deletar)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(212, 212, 212))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(16, 16, 16)
                                .addComponent(txt_ProfissionalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ProfissionalNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ProfissionalPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ProfissionalPesqProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProfissionalProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProfissionalSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProfissionalAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ProfissionalCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_limpar)
                            .addComponent(btn_salvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_deletar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ProfissionalNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProfissionalNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProfissionalNomeActionPerformed

    private void txt_ProfissionalPesqNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProfissionalPesqNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProfissionalPesqNomeActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String profissional_id = txt_ProfissionalId.getText();
        String profissional_nome = txt_ProfissionalNome.getText();
        String profissional_profissao = txt_ProfissionalProfissao.getText();
        String profissional_salario = txt_ProfissionalSalario.getText();
        String profissional_areaAtuacao = txt_ProfissionalAreaAtuacao.getText();
        String profissional_cargo = txt_ProfissionalCargo.getText();
        
        if(!"0".equals(profissional_id))
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
                     
            try { conn = DBConexao.abrirConexao();} catch (Exception ex){ Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            Statement stm = null;
            try { stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}

            String sql;
            sql = "UPDATE profissional SET "
                    + "profissional_nome = '"+ profissional_nome +"', "
                    + "profissional_profissao = '"+ profissional_profissao +"', "
                    + "profissional_salario = '"+ profissional_salario +"', "
                    + "profissional_areaAtuacao = '"+ profissional_areaAtuacao +"', "
                    + "profissional_cargo = '"+ profissional_cargo +"' "            
                    + "WHERE profissional_id = "+ profissional_id +";";
            try {stm.executeUpdate(sql);} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");

            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
        }
        else
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
            try { conn = DBConexao.abrirConexao();} catch (Exception ex){ Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            

            Statement stm = null;
            try { stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            String query;
            query = "INSERT INTO profissional(profissional_nome, profissional_profissao, profissional_salario, profissional_areaAtuacao, profissional_cargo) VALUES "
                        + "('"+ profissional_nome +"','"
                            + profissional_profissao +"','"
                            + profissional_salario +"','"
                            + profissional_areaAtuacao +"','"
                            + profissional_cargo + "');";
            try { stm.executeUpdate(query);} catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}

            JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso");

            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
        }
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void tbview_ProfissionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbview_ProfissionalMouseClicked
        // TODO add your handling code here:
        int linha = tbview_Profissional.getSelectedRow(); 
        txt_ProfissionalId.setText(tbview_Profissional.getValueAt(linha,0).toString()); 
        txt_ProfissionalNome.setText(tbview_Profissional.getValueAt(linha,1).toString()); 
        txt_ProfissionalProfissao.setText(tbview_Profissional.getValueAt(linha,2).toString());
        txt_ProfissionalSalario.setText(tbview_Profissional.getValueAt(linha,3).toString()); 
        txt_ProfissionalAreaAtuacao.setText(tbview_Profissional.getValueAt(linha,4).toString()); 
        txt_ProfissionalCargo.setText(tbview_Profissional.getValueAt(linha,5).toString());
    }//GEN-LAST:event_tbview_ProfissionalMouseClicked

    private void btn_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesqActionPerformed
        // TODO add your handling code here:
        String profissional_nome = txt_ProfissionalPesqNome.getText();
        String profissional_profissao = txt_ProfissionalPesqProfissao.getText();
        
        Connection conn = null;
        ResultSet resultadoBanco = null;
        
        try { conn = DBConexao.abrirConexao();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        Statement stm = null;     
        try {stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        String sql;
        String sql1 = null;
        if(!"".equals(profissional_nome)){ sql1 = " WHERE profissional_nome LIKE '%"+ profissional_nome +"%' ";}
        else if(!"".equals(profissional_profissao)){ sql1 = " WHERE profissional_profissao LIKE '%"+ profissional_profissao +"%' ";}
        else if(!"".equals(profissional_profissao) && !"".equals(profissional_nome)){ sql1 = " WHERE profissional_nome '%"+profissional_nome+"%' && profissional_profissao LIKE '%"+ profissional_profissao +"%' ";}
        else{sql1 = "";}
        sql = "SELECT * FROM profissional "
                + sql1 
                + " ;";
        try { resultadoBanco = stm.executeQuery(sql);} catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        DefaultTableModel model =(DefaultTableModel) tbview_Profissional.getModel();
        model.setNumRows(0);

        try 
        {
            while(resultadoBanco.next())
            {
                model.addRow(new Object[]
                {
                    //retorna os dados da tabela do BD, cada campo e um coluna.
                    resultadoBanco.getString("profissional_id"),
                    resultadoBanco.getString("profissional_nome"),
                    resultadoBanco.getString("profissional_profissao"),
                    resultadoBanco.getString("profissional_salario"),
                    resultadoBanco.getString("profissional_areaAtuacao"),
                    resultadoBanco.getString("profissional_cargo")
                }); 
            }
        } catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_btn_pesqActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        txt_ProfissionalAreaAtuacao.setText("");
        txt_ProfissionalCargo.setText("");
        txt_ProfissionalId.setText("0");
        txt_ProfissionalNome.setText("");
        txt_ProfissionalProfissao.setText("");
        txt_ProfissionalSalario.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        // TODO add your handling code here:
        
        int linha = tbview_Profissional.getSelectedRow(); 
        String profissionalId = tbview_Profissional.getValueAt(linha,0).toString();
        
        Connection conn = null;
        ResultSet resultadoBanco = null;
                     
        try {conn = DBConexao.abrirConexao();} catch (Exception ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        Statement stm = null;
        try { stm = conn.createStatement(); } catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        String message = "Deseja realmente apagar o registro?";
        String title = "Confirmação";

        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            String sql;
            sql = "DELETE FROM profissional WHERE profissional_id = " +profissionalId+";";
            try { stm.executeUpdate(sql); } catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
            btn_limparActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Form_Principal().setVisible(true);
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Profissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Profissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Profissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Profissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_Profissional().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Form_Profissional.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_pesq;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbview_Profissional;
    private javax.swing.JTextField txt_ProfissionalAreaAtuacao;
    private javax.swing.JTextField txt_ProfissionalCargo;
    private javax.swing.JTextField txt_ProfissionalId;
    private javax.swing.JTextField txt_ProfissionalNome;
    private javax.swing.JTextField txt_ProfissionalPesqNome;
    private javax.swing.JTextField txt_ProfissionalPesqProfissao;
    private javax.swing.JTextField txt_ProfissionalProfissao;
    private javax.swing.JTextField txt_ProfissionalSalario;
    // End of variables declaration//GEN-END:variables
}
