/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp1_e5;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MaXx
 */
public class Form_Calcado extends javax.swing.JFrame {

    /**
     * Creates new form Form_Calcado
     */
    public Form_Calcado() throws Exception {
        initComponents();
        PopularJTable();
    }
    public void PopularJTable() throws Exception 
    {
        try
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
            conn = DBConexao.abrirConexao();
            Statement stm = conn.createStatement();
                
            String sql0;
            sql0 = "SELECT * FROM calcado ";
            resultadoBanco = stm.executeQuery(sql0);
         
            DefaultTableModel model =(DefaultTableModel) tbview_calcado.getModel();
            model.setNumRows(0);

            while(resultadoBanco.next())
            {
                model.addRow(new Object[] 
                { 
                   //retorna os dados da tabela do BD, cada campo e um coluna.
                   resultadoBanco.getString("calcado_id"),
                   resultadoBanco.getString("calcado_marca"),
                   resultadoBanco.getString("calcado_modelo"),
                   resultadoBanco.getString("calcado_valor"),
                   resultadoBanco.getString("calcado_tipo"),
                   resultadoBanco.getString("calcado_cor")
                }); 
            } 

        }
       catch (SQLException ex){System.out.println("o erro foi " +ex);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_calcadoMarca = new javax.swing.JTextField();
        txt_calcadoModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_calcadoCor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_calcadoValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_calcadoTipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_calcadoPesqCor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_calcadoPesqMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbview_calcado = new javax.swing.JTable();
        btn_limpar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        btn_pesquisar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        txt_calcadoId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MARCA:");

        jLabel2.setText("MODELO:");

        jLabel3.setText("COR:");

        jLabel4.setText("VALOR:");

        jLabel5.setText("TIPO:");

        jLabel6.setText("COR:");

        jLabel7.setText("MARCA:");

        tbview_calcado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MARCA", "MODELO", "VALOR", "TIPO", "COR"
            }
        ));
        tbview_calcado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbview_calcadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbview_calcado);

        btn_limpar.setText("LIMPAR");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_salvar.setText("SALVAR");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_deletar.setText("DELETAR");
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        btn_pesquisar.setText("PESQUISAR");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_voltar.setText("VOLTAR");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        txt_calcadoId.setEditable(false);
        txt_calcadoId.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_calcadoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_calcadoId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_calcadoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_calcadoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_calcadoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_calcadoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_limpar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txt_calcadoPesqCor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_calcadoPesqMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_pesquisar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_deletar)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_calcadoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_calcadoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_calcadoPesqMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_calcadoPesqCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_calcadoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_calcadoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txt_calcadoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_calcadoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_limpar)
                            .addComponent(btn_salvar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deletar)
                    .addComponent(btn_voltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String calcado_id = txt_calcadoId.getText();
        String calcado_marca = txt_calcadoMarca.getText();
        String calcado_modelo = txt_calcadoModelo.getText();
        String calcado_valor = txt_calcadoValor.getText();
        String calcado_tipo = txt_calcadoTipo.getText();
        String calcado_cor = txt_calcadoCor.getText();

        if(!"0".equals(calcado_id))
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
                     
            try { conn = DBConexao.abrirConexao();} catch (Exception ex){ Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            Statement stm = null;
            try { stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}

            String sql;
            sql = "UPDATE calcado SET "
                    + "calcado_marca = '"+ calcado_marca +"', "
                    + "calcado_modelo = '"+ calcado_modelo +"', "
                    + "calcado_valor = '"+ calcado_valor +"', "
                    + "calcado_tipo = '"+ calcado_tipo +"', "
                    + "calcado_cor = '"+ calcado_cor +"' "            
                    + "WHERE calcado_id = "+ calcado_id +";";
            try {stm.executeUpdate(sql);} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");

            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
        }
        else
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
            try { conn = DBConexao.abrirConexao();} catch (Exception ex){ Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            

            Statement stm = null;
            try { stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            String query;
            query = "INSERT INTO calcado(calcado_marca, calcado_modelo, calcado_valor, calcado_tipo, calcado_cor) VALUES "
                        + "('"+ calcado_marca +"','"
                            + calcado_modelo +"','"
                            + calcado_valor +"','"
                            + calcado_tipo +"','"
                            + calcado_cor + "');";
            try { stm.executeUpdate(query);} catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}

            JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso");

            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        txt_calcadoCor.setText("");
        txt_calcadoId.setText("0");
        txt_calcadoMarca.setText("");
        txt_calcadoModelo.setText("");
        txt_calcadoTipo.setText("");
        txt_calcadoValor.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        // TODO add your handling code here:
        int linha = tbview_calcado.getSelectedRow(); 
        String calcadoId = tbview_calcado.getValueAt(linha,0).toString();
        
        Connection conn = null;
        ResultSet resultadoBanco = null;
                     
        try {conn = DBConexao.abrirConexao();} catch (Exception ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        Statement stm = null;
        try { stm = conn.createStatement(); } catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        String message = "Deseja realmente apagar o registro?";
        String title = "Confirmação";

        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            String sql;
            sql = "DELETE FROM calcado WHERE calcado_id = " +calcadoId+";";
            try { stm.executeUpdate(sql); } catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
            btn_limparActionPerformed(evt);
        }
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        // TODO add your handling code here:
        String calcado_marca = txt_calcadoPesqMarca.getText();
        String calcado_cor = txt_calcadoPesqCor.getText();
        
        Connection conn = null;
        ResultSet resultadoBanco = null;
        
        try { conn = DBConexao.abrirConexao();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        Statement stm = null;     
        try {stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        String sql;
        String sql1 = null;
        if(!"".equals(calcado_marca)){ sql1 = " WHERE calcado_marca LIKE '%"+ calcado_marca +"%' ";}
        else if(!"".equals(calcado_cor)){ sql1 = " WHERE calcado_cor LIKE '%"+ calcado_cor +"%' ";}
        else if(!"".equals(calcado_cor) && !"".equals(calcado_marca)){ sql1 = " WHERE calcado_marca '%"+calcado_marca+"%' && calcado_cor LIKE '%"+ calcado_cor +"%' ";}
        else{sql1 = "";}
        sql = "SELECT * FROM calcado "
                + sql1 
                + " ;";
        try { resultadoBanco = stm.executeQuery(sql);} catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        DefaultTableModel model =(DefaultTableModel) tbview_calcado.getModel();
        model.setNumRows(0);

        try 
        {
            while(resultadoBanco.next())
            {
                model.addRow(new Object[]
                {
                    //retorna os dados da tabela do BD, cada campo e um coluna.
                    resultadoBanco.getString("calcado_id"),
                    resultadoBanco.getString("calcado_marca"),
                    resultadoBanco.getString("calcado_modelo"),
                    resultadoBanco.getString("calcado_valor"),
                    resultadoBanco.getString("calcado_tipo"),
                    resultadoBanco.getString("calcado_cor")
                }); 
            }
        } catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Form_Principal().setVisible(true);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void tbview_calcadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbview_calcadoMouseClicked
        // TODO add your handling code here:
        int linha = tbview_calcado.getSelectedRow(); 
        txt_calcadoId.setText(tbview_calcado.getValueAt(linha,0).toString()); 
        txt_calcadoMarca.setText(tbview_calcado.getValueAt(linha,1).toString()); 
        txt_calcadoModelo.setText(tbview_calcado.getValueAt(linha,2).toString()); 
        txt_calcadoValor.setText(tbview_calcado.getValueAt(linha,3).toString());
        txt_calcadoTipo.setText(tbview_calcado.getValueAt(linha,4).toString()); 
        txt_calcadoCor.setText(tbview_calcado.getValueAt(linha,5).toString()); 
        
    }//GEN-LAST:event_tbview_calcadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Calcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Calcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Calcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Calcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_Calcado().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Form_Calcado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbview_calcado;
    private javax.swing.JTextField txt_calcadoCor;
    private javax.swing.JTextField txt_calcadoId;
    private javax.swing.JTextField txt_calcadoMarca;
    private javax.swing.JTextField txt_calcadoModelo;
    private javax.swing.JTextField txt_calcadoPesqCor;
    private javax.swing.JTextField txt_calcadoPesqMarca;
    private javax.swing.JTextField txt_calcadoTipo;
    private javax.swing.JTextField txt_calcadoValor;
    // End of variables declaration//GEN-END:variables
}
